[package]
name = "querycraft"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "mysql", "postgres"] }
tokio = { version = "1", features = ["full"] }
axum = "0.7"